//! Build script: generates embedded.rs from checked-in plugins.
//!
//! This is the single source of truth for plugin configs in the binary.
//! The generated file lives under OUT_DIR so clean clones do not depend on
//! ignored source files under src/.
//!
//! Flow:
//!   1. cargo build triggers this build.rs
//!   2. Reads all plugin.toml and tags.scm from checked-in plugins/
//!   3. Generates $OUT_DIR/embedded.rs
//!   4. Compiler includes the generated file

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let plugins_dir = Path::new("../plugins");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR missing");
    let out_path = PathBuf::from(out_dir).join("embedded.rs");

    println!("cargo:rerun-if-changed=../plugins");

    if !plugins_dir.exists() || !plugins_dir.is_dir() {
        write_embedded_file(&out_path, &[]);
        println!(
            "cargo:warning=plugins/ directory not found, generating empty embedded plugin set"
        );
        return;
    }

    let mut entries: Vec<(String, String, String)> = Vec::new();
    let mut dirs: Vec<_> = fs::read_dir(plugins_dir)
        .expect("failed to read plugins/")
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.path().is_dir())
        .collect();
    dirs.sort_by_key(|entry| entry.file_name());

    for entry in &dirs {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }

        let toml_path = entry.path().join("plugin.toml");
        if !toml_path.exists() {
            continue;
        }
        let toml_content = fs::read_to_string(&toml_path)
            .unwrap_or_else(|error| panic!("failed to read {}: {}", toml_path.display(), error));

        let scm_path = entry.path().join("queries").join("tags.scm");
        let scm_content = if scm_path.exists() {
            fs::read_to_string(&scm_path)
                .unwrap_or_else(|error| panic!("failed to read {}: {}", scm_path.display(), error))
        } else {
            String::new()
        };

        entries.push((name.clone(), toml_content, scm_content));
        println!("cargo:rerun-if-changed=../plugins/{}/plugin.toml", name);
        println!(
            "cargo:rerun-if-changed=../plugins/{}/queries/tags.scm",
            name
        );
    }

    if write_embedded_file(&out_path, &entries) {
        println!(
            "cargo:warning=Generated embedded.rs with {} plugins",
            entries.len()
        );
    }
}

fn write_embedded_file(out_path: &Path, entries: &[(String, String, String)]) -> bool {
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from checked-in plugins.\n");
    code.push_str("// DO NOT EDIT MANUALLY — changes will be overwritten on next build.\n");
    code.push_str("//\n");
    code.push_str(&format!("// Generated from {} plugins.\n\n", entries.len()));
    code.push_str("/// (name, plugin_toml_content, tags_scm_content)\n");
    code.push_str("pub const EMBEDDED_PLUGINS: &[(&str, &str, &str)] = &[\n");

    for (name, toml, scm) in entries {
        let toml_delimiter = find_safe_delim(toml);
        let scm_delimiter = find_safe_delim(scm);
        code.push_str("    (\n");
        code.push_str(&format!("        \"{name}\",\n"));
        code.push_str(&format!(
            "        r{toml_delimiter}\"{toml}\"{toml_delimiter},\n"
        ));
        code.push_str(&format!(
            "        r{scm_delimiter}\"{scm}\"{scm_delimiter},\n"
        ));
        code.push_str("    ),\n");
    }

    code.push_str("];\n");

    let existing = fs::read_to_string(out_path).unwrap_or_default();
    if existing == code {
        return false;
    }

    fs::write(out_path, &code)
        .unwrap_or_else(|error| panic!("failed to write {}: {}", out_path.display(), error));
    true
}

/// Find minimum number of # for a safe raw string delimiter.
fn find_safe_delim(content: &str) -> String {
    let mut count = 1;
    loop {
        let hashes = "#".repeat(count);
        if !content.contains(&format!("\"{}", hashes))
            && !content.contains(&format!("{}\"", hashes))
        {
            return hashes;
        }
        count += 1;
    }
}
